
	[19136] = {
		unidentifiedDisplayName = "Helm",
		unidentifiedResourceName = "Çï¸§",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with ^008080Magnifier^000000." },
		identifiedDisplayName = "Spirit of Chung E",
		identifiedResourceName = "Ã»ÀÌÀÇ¿µÈ¥",
		identifiedDescriptionName = {
			"Chung E's soul floating above your head.",
			"_______________________",
			"Increase exp gain by 1%, item drop rate by 1% per 2 refine rates. ",
			"MaxHP + 2%, MaxSP + 2% per 4 refine rates.",
			"_______________________",
			"When refined to +9 or higher,",
			"HP recovery + 40%, SP Recovery + 40%.",
			"_______________________",
			"When refined to +12 or higher,",
			"MaxHP + 3%, MaxSP + 3%.",
			"_______________________",
			"When melee, physically attacking, adds a chance to transform into Chung E for 5 seconds. ",
			"When transformed, MATK + 30%, Critical Damage + 30%.",
			"_______________________",
			"Type : ^777777Helm^000000 Defense : ^7777770^000000",
			"Location : ^777777Upper ^000000Weight : ^7777771^000000",
			"Required Level : ^7777771^000000",
			"Class : ^777777All^000000"
		},
		slotCount = 1,
		ClassNum = 882,
		costume = false
	},
	[102813] = {
		unidentifiedDisplayName = "Eps 17 - 18 MVP Card Album",
		unidentifiedResourceName = "R_Ep178_boss",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Eps 17 - 18 MVP Card Album",
		identifiedResourceName = "R_Ep178_boss",
		identifiedDescriptionName = {
			"A card album decorated with runic letters.",
			"You can obtain one Boss Monster Card from Episodes 17 and 18.",
			"_______________________",
			"R48-85-BESTIA Card 9,09%",
			"EL-A17T Card 9,09%",
			"Red Pepper Card 9,09%",
			"Silva Papilia Card 9,09%",
			"Gran Papilia Card 9,09%",
			"Sweetie Card 9,09%",
			"Meow Card 9,10%",
			"Miguel Card 9,09%",
			"Burning Fang Card 9,09%",
			"Twisted God Card 9,09%",
			"Schulang Card 9,09%",
			"_______________________",
			"^ff0000Caution! - Contains only cards related to the Episode 17 and Episode 18 Rune Tablets.^000000",
			"_______________________",
			"^ff0000Account Bound^000000",
			"_______________________",
			"Weight : ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[103331] = {
		unidentifiedDisplayName = "MVP Card Album (Selection)",
		unidentifiedResourceName = "µ¥¸óºÏ",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "MVP Card Album (Selection)",
		identifiedResourceName = "µ¥¸óºÏ",
		identifiedDescriptionName = {
			"When opened, choose 1 MVP card of your choice.",
			"You can choose one of the following MVP Card:",
			"_______________________",
			"Moonlight Flower Card",
			"     ",
			"Mistress Card",
			"     ",
			"Orc Lord Card",
			"     ",
			"Drake Card",
			"     ",
			"Turtle General Card",
			"     ",
			"Vesper Card",
			"     ",
			"Randgris Card",
			"     ",
			"Gloom Under Night Card",
			"     ",
			"Pyuriel Card",
			"     ",
			"Time Holder Card",
			"_______________________",
			"^FF0000Account Bound^000000",
			"_______________________",
			"Weight : ^7777771^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[105529] = {
		unidentifiedDisplayName = "[Event] Velcarde MVP Card Album",
		unidentifiedResourceName = "Vivatus_F_Star_B",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "[Event] Velcarde MVP Card Album",
		identifiedResourceName = "Vivatus_F_Star_B",
		identifiedDescriptionName = {
			"^ff0000Cannot be traded.^000000",
			"A card album compiled by Velcarde. You can sense the aura of powerful monsters from within.",
			"When opened gives one of the following:",
			"_______________________",
			"Fenrir Card 7,00%",
			"Cursed King Schmidt Card 7,00%",
			"Cutie Card 7,00%",
			"Dracula Card 7,00%",
			"Hatii Card 7,00%",
			"Ifrit Card 7,00%",
			"Ktullanux Card 7,00%",
			"Kiel-D-01 Card 7,00%",
			"Fallen Bishop Card 7,00%",
			"Dark Lord Card 7,00%",
			"Sealed Kiel Card 6,00%",
			"Sealed Ktullanux Card 6,00%",
			"SLD Garm Card 6,00%",
			"Sealed Ifrit Card 6,00%",
			"Sealed Dark Lord Card 6,00%",
			"_______________________",
			"Weight : ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[300784] = {
		unidentifiedDisplayName = "Shadow Cross Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Shadow Cross Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Katar:",
			"Critical damage +30%.",
			"Increases the damage of [Eternal Slash] and [Savage Impact] by 5% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Katar is Grade C or higher:",
			"Reduces the cooldown of [Savage Impact] by 0.6 seconds.",
			"     ",
			"If Dim Glacier Katar is Grade C or higher and refined to +12 or higher:",
			"Has a 10% chance to trigger [Weapon Blocking Counter] effect for 10 seconds when using [Savage Impact].",
			"Has a 40% chance to auto-cast [Eternal Slash] Lv.1 when using [Savage Impact] (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Eternal Slash] and [Savage Impact] by 20%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[300785] = {
		unidentifiedDisplayName = "Shinkiro&Shiranui Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Shadow Cross Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Huuma Shuriken:",
			"Critical damage +30%.",
			"Increases the damage of [Shadow Flash] by 5% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Huuma Shuriken is Grade C or higher:",
			"Reduces the cooldown of [Shadow Flash] by 0.35 seconds.",
			"     ",
			"If Dim Glacier Huuma Shuriken is Grade C or higher and refined to +12 or higher:",
			"Has a 30% chance to auto-cast [Shadow Flash] Lv.1 when using [Shadow Flash] (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Shadow Flash] by 20%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[314811] = {
		unidentifiedDisplayName = "Abyss Chaser Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Abyss Chaser Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Rogue Knife:",
			"Increases magical damage against targets of all properties by 5%.",
			"Increases the damage of [Abyss Square] and [Jack Frost Nova] by 4% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Rogue Knife is Grade C or higher:",
			"Reduces the cooldown of [Abyss Square] by 1 second.",
			"     ",
			"If Dim Glacier Rogue Knife is Grade C or higher and refined to +12 or higher:",
			"Has a 15% chance to auto-cast [Jack Frost Nova] Lv.10 when dealing physical damage.",
			"Increases the damage of [Abyss Square] and [Jack Frost Nova] by 15%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[314812] = {
		unidentifiedDisplayName = "Inquisitor Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Inquisitor Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Knuckle:",
			"Increases physical damage against targets of all properties by 5%.",
			"Increases the damage of [Third Flame Bomb] by 4% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Knuckle is Grade C or higher:",
			"MaxHP +15%.",
			"     ",
			"If Dim Glacier Knuckle is Grade C or higher and refined to +12 or higher:",
			"Auto-casts [Second Flame] Lv.1 when using [First Brand] (If a higher level is learned, casts the highest level learned).",
			"Auto-casts [Third Flame Bomb] Lv.1 when using [Second Flame] (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Third Flame Bomb] by 15%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[314821] = {
		unidentifiedDisplayName = "Windhawk Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Windhawk Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Bow:",
			"Critical damage +30%.",
			"Increases the damage of [Hawk Rush] by 5% and [Focused Arrow Strike] by 20% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Bow is Grade C or higher:",
			"Reduces physical and magical damage taken from targets of all sizes by 30%.",
			"     ",
			"If Dim Glacier Bow is Grade C or higher and refined to +12 or higher:",
			"Has a 40% chance to auto-cast [Focused Arrow Strike] Lv.5 when using [Hawk Rush].",
			"Increases the damage of [Hawk Rush] by 20% and [Focused Arrow Strike] by 50%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[314905] = {
		unidentifiedDisplayName = "Meister Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Meister Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Mechanic Mace:",
			"Increases ranged physical damage by 15%.",
			"Increases the damage of [Spark Blaster] by 4% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Mechanic Mace is Grade C or higher:",
			"Reduces the cooldown of [Spark Blaster] by 0.35 seconds.",
			"     ",
			"If Dim Glacier Mechanic Mace is Grade C or higher and refined to +12 or higher:",
			"Has a 30% chance to auto-cast [Spark Blaster] Lv.1 when using [Spark Blaster] (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Spark Blaster] by 15%.",
			"Enables [Power] Lv.4."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[314985] = {
		unidentifiedDisplayName = "Arch Mage Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Arch Mage Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Staff:",
			"Increases magical damage against targets of all properties by 15%.",
			"Increases the damage of [Mystery Illusion] by 5% and [Comet] by 20% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Staff is Grade C or higher:",
			"Reduces physical and magical damage taken from targets of all sizes by 30%.",
			"Reduces the cooldown of [Mystery Illusion] by 1.65 seconds.",
			"     ",
			"If Dim Glacier Staff is Grade C or higher and refined to +12 or higher:",
			"Reduces the cooldown of [Mystery Illusion] by 1.65 seconds.",
			"Reduces the cooldown of [Comet] by 20 seconds.",
			"Increases the damage of [Mystery Illusion] by 20%.",
			"Increases the damage of [Comet] by 50%.",
			"     ",
			"_______________________",
			"     ",
			"When equipped with Dim Glacier Wand:",
			"Increases magical damage against targets of all properties by 10%.",
			"Increases the damage of [Mystery Illusion] by 4% and [Comet] by 10% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Wand is Grade C or higher:",
			"Reduces the cooldown of [Mystery Illusion] by 1.5 seconds.",
			"     ",
			"If Dim Glacier Wand is Grade C or higher and refined to +12 or higher:",
			"Reduces the cooldown of [Mystery Illusion] by 1.5 seconds.",
			"Increases the damage of [Mystery Illusion] by 15%.",
			"Increases the damage of [Comet] by 25%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[314986] = {
		unidentifiedDisplayName = "Dragon Knight Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Dragon Knight Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Two-handed Sword or Dim Glacier Lance:",
			"Increases ranged physical damage by 20%.",
			"Increases the damage of [Dragonic Breath] by 5% for every 2 refine levels of the weapon.",
			"",
			"If Dim Glacier Two-handed Sword or Dim Glacier Lance is Grade C or higher:",
			"Reduces the cooldown of [Dragonic Breath] by 0.25 seconds.",
			"",
			"If Dim Glacier Two-handed Sword or Dim Glacier Lance is Grade C or higher and refined to +12 or higher:",
			"MaxHP +10%, MaxSP +10%.",
			"Reduces variable casting time of [Dragonic Breath] by 100%.",
			"Has a 30% chance to auto-cast [Dragonic Breath] Lv.1 when using [Dragonic Breath] (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Dragonic Breath] by 20%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[314904] = {
		unidentifiedDisplayName = "Cardinal Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Cardinal Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Book or Dim Glacier Mace:",
			"Critical damage +15%.",
			"Increases the damage of [Petitio] by 4% for every 2 refine levels of the weapon.",
			"",
			"If Dim Glacier Book or Dim Glacier Mace is Grade C or higher:",
			"Increases melee and ranged physical damage by 20%.",
			"",
			"If Dim Glacier Book or Dim Glacier Mace is Grade C or higher and refined to +12 or higher:",
			"Enables [Charge Attack] Lv.1.",
			"Has a 30% chance to auto-cast [Petitio] Lv.1 when using [Petitio] (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Petitio] by 15%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[314906] = {
		unidentifiedDisplayName = "Troubadour & Trouvere Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Troubadour & Trouvere Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Violin or Dim Glacier Whip:",
			"Increases ranged physical damage by 15%.",
			"Increases the damage of [Rhythm Shooting] by 4% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Violin or Dim Glacier Whip is Grade C or higher:",
			"Reduces the cooldown of [Rhythm Shooting] by 0.15 seconds.",
			"     ",
			"If Dim Glacier Violin or Dim Glacier Whip is Grade C or higher and refined to +12 or higher:",
			"Has a 30% chance to auto-cast [Rhythm Shooting] Lv.1 when using [Rhythm Shooting] (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Rhythm Shooting] by 15%.",
			"Enables [Power] Lv.4."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[315109] = {
		unidentifiedDisplayName = "Imperial Guard Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Imperial Guard Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Spear:",
			"Increases ranged physical damage by 15%.",
			"Increases the damage of [Shield Shooting] by 4% and [Cannon Spear] by 20% for every 2 refine levels of the weapon.",
			"",
			"If Dim Glacier Spear is Grade C or higher:",
			"Reduces the cooldown of [Shield Shooting] by 0.5 seconds.",
			"CRI +30.",
			"",
			"If Dim Glacier Spear is Grade C or higher and refined to +12 or higher:",
			"Has a 30% chance to auto-cast [Shield Shooting] Lv.1 when using [Shield Shooting] (If a higher level is learned, casts the highest level learned).",
			"Has a 30% chance to auto-cast [Cannon Spear] Lv.1 when using [Cannon Spear] (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Shield Shooting] by 15% and [Cannon Spear] by 50%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[315110] = {
		unidentifiedDisplayName = "Hyper Novice Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Hyper Novice Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Basic Knife or Dim Glacier Basic Sword:",
			"Critical damage +30%.",
			"Increases the damage of [Mega Sonic Blow] by 4% for every 2 refine levels of the weapon.",
			"",
			"If Dim Glacier Basic Knife or Dim Glacier Basic Sword is Grade C or higher:",
			"Reduces the cooldown of [Mega Sonic Blow] by 0.15 seconds.",
			"",
			"If Dim Glacier Basic Knife or Dim Glacier Basic Sword is Grade C or higher and refined to +12 or higher:",
			"Has a 30% chance to auto-cast [Mega Sonic Blow] Lv.1 when using [Mega Sonic Blow] (If a higher level is learned, casts the highest level learned).",
			"Enables [Enchant Deadly Poison] Lv.5 (The skill effect is canceled when the equipment is removed).",
			"Increases the damage of [Mega Sonic Blow] by 15%.",
			"     ",
			"_______________________",
			"     ",
			"When equipped with Dim Glacier Wand:",
			"Increases magical damage against targets of all properties by 10%.",
			"Increases the damage of [Jack Frost Nova] by 4% for every 2 refine levels of the weapon.",
			"",
			"If Dim Glacier Wand is Grade C or higher:",
			"Reduces the cooldown of [Jack Frost Nova] by 1.5 seconds.",
			"",
			"If Dim Glacier Wand is Grade C or higher and refined to +12 or higher:",
			"Reduces the cooldown of [Jack Frost Nova] by 1 second.",
			"Enables [Energy Coat] Lv.1 (The skill effect is canceled when the equipment is removed).",
			"Increases Water property magical damage by 20%.",
			"Increases the damage of [Jack Frost Nova] by 15%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[315111] = {
		unidentifiedDisplayName = "Sky Emperor Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Sky Emperor Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Book:",
			"Increases melee physical damage by 15%.",
			"Increases the damage of [Twinkling Galaxy] and [Star Cannon] by 5% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Book is Grade C or higher:",
			"Reduces the cooldown of [Twinkling Galaxy] by 2 seconds and [Star Cannon] by 1.5 seconds.",
			"    ",
			"If Dim Glacier Book is Grade C or higher and refined to +12 or higher:",
			"Reduces the cooldown of [Twinkling Galaxy] by 2 seconds and [Star Cannon] by 1.5 seconds.",
			"Has a 50% chance to restore 1% of physical damage dealt as HP when dealing physical attacks",
			"Increases the damage of [Twinkling Galaxy] and [Star Cannon] by 15%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[315112] = {
		unidentifiedDisplayName = "Elemental Master Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Elemental Master Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Book:",
			"Increases magical damage against targets of all properties by 10%.",
			"Increases the damage of [Conflagration] and [Lightning Land] by 5% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Book is Grade C or higher:",
			"Reduces the cooldown of [Conflagration] and [Lightning Land] by 1 second.",
			"     ",
			"If Dim Glacier Book is Grade C or higher and refined to +12 or higher:",
			"Increases Fire and Wind property magical damage by 20%.",
			"Increases the damage of [Conflagration] and [Lightning Land] by 15%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[315113] = {
		unidentifiedDisplayName = "Windhawk Dim Gale Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Windhawk Dim Gale Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Bow:",
			"Critical damage +30%.",
			"Increases the damage of [Hawk Rush] and [Gale Storm] by 5% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Bow is Grade C or higher:",
			"Reduces the cooldown of [Gale Storm] by 1.2 seconds.",
			"     ",
			"If Dim Glacier Bow is Grade C or higher and refined to +12 or higher:",
			"Has a 15% chance to auto-cast [Gale Storm] Lv.1 when dealing ranged physical attacks (If a higher level is learned, casts the highest level learned).",
			"Has a 30% chance to auto-cast [Gale Storm] Lv.1 when using [Gale Storm] (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Hawk Rush] and [Gale Storm] by 20%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[315161] = {
		unidentifiedDisplayName = "Spirit Handler Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Spirit Handler Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Foxtail:",
			"Increases magical damage against targets of all properties by 10%.",
			"Increases the damage of [Hyunrok Breeze] by 4% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Foxtail is Grade C or higher:",
			"Reduces the cooldown of [Hyunrok Breeze] by 2.5 seconds.",
			"     ",
			"If Dim Glacier Foxtail is Grade C or higher and refined to +12 or higher:",
			"Reduces the cooldown of [Lope] by 3 seconds.",
			"Has a 4% chance to grant [Glacier Breeze] status for 10 seconds when dealing magical attacks.",
			"Increases the damage of [Hyunrok Breeze] by 15%.",
			"     ",
			"[Glacier Breeze] Effect:",
			"SPL +60.",
			"S.MATK +15.",
			"Drains 500 HP per second."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[315162] = {
		unidentifiedDisplayName = "Biolo Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Biolo Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Mace or Dim Glacier Sword:",
			"Critical damage +30%.",
			"Increases the damage of [Mayhemic Thorns] by 4% for every 2 refine levels of the weapon.",
			"",
			"If Dim Glacier Mace or Dim Glacier Sword is Grade C or higher:",
			"Reduces the cooldown of [Mayhemic Thorns] by 0.4 seconds.",
			"",
			"If Dim Glacier Mace or Dim Glacier Sword is Grade C or higher and refined to +12 or higher:",
			"P.ATK +10.",
			"Increases ranged physical damage by 20%.",
			"Grants POW +50 for 10 seconds when using [Research Report].",
			"Increases the damage of [Mayhemic Thorns] by 15%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[315163] = {
		unidentifiedDisplayName = "Night Watch Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Night Watch Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Revolver:",
			"Critical damage +30%.",
			"Increases the damage of [Magazine for One] by 5% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Revolver is Grade C or higher:",
			"Reduces the cooldown of [Magazine for One] by 0.4 seconds.",
			"CRI +30.",
			"     ",
			"If Dim Glacier Revolver is Grade C or higher and refined to +12 or higher:",
			"Has a 30% chance to auto-cast [Magazine for One] Lv.1 when using [Magazine for One] (If a higher level is learned, casts the highest level learned).",
			"Has a 15% chance to auto-cast [Magazine for One] Lv.1 when dealing ranged physical damage (If a higher level is learned, casts the highest level learned).",
			"Increases the damage of [Magazine for One] by 20%.",
			"     ",
			"_______________________",
			"     ",
			"When equipped with Dim Glacier Gatling Gun:",
			"Increases ranged physical damage by 15%.",
			"Increases the damage of [The Vigilante at Night] by 5% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Gatling Gun is Grade C or higher:",
			"Reduces the cooldown of [The Vigilante at Night] by 0.5 seconds.",
			"     ",
			"If Dim Glacier Gatling Gun is Grade C or higher and refined to +12 or higher:",
			"Enables [Power] Lv.4.",
			"Grants CON +50 for 10 seconds when using [Hidden Card].",
			"Increases the damage of [The Vigilante at Night] by 20%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[315164] = {
		unidentifiedDisplayName = "Soul Ascetic Dim Crystal",
		unidentifiedResourceName = "Sea_Sapphire",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Soul Ascetic Dim Crystal",
		identifiedResourceName = "Sea_Sapphire",
		identifiedDescriptionName = {
			"When equipped with Dim Glacier Wand:",
			"Increases magical damage against targets of all properties by 10%.",
			"Increases the damage of [Talisman of Black Tortoise] and [Talisman of White Tiger] by 5% for every 2 refine levels of the weapon.",
			"     ",
			"If Dim Glacier Wand is Grade C or higher:",
			"Reduces the cooldown of [Talisman of Black Tortoise] by 0.5 seconds.",
			"Reduces the cooldown of [Talisman of White Tiger] by 0.2 seconds.",
			"     ",
			"If Dim Glacier Wand is Grade C or higher and refined to +12 or higher:",
			"Increases magical damage of all properties by 20%.",
			"Enables [Energy Coat] Lv.1.",
			"Increases the damage of [Talisman of Black Tortoise] and [Talisman of White Tiger] by 15%."
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[400948] = {
		unidentifiedDisplayName = "Headgear",
		unidentifiedResourceName = "¸Ó¸®¶ì",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Robotic Valkyrie Hairband",
		identifiedResourceName = "±â°è±êÅÐÇì¾î¹êµå",
		identifiedDescriptionName = {
			"A hairband adorned with precision mechanical decorations. A masterpiece modeled after a Valkyrie helmet.",
			"_______________________",
			"Increases ranged physical damage by 30%.",
			"_______________________",
			"For every 2 refine levels,",
			"POW +1, ranged physical damage +5%.",
			"_______________________",
			"For every 3 refine levels,",
			"Triple Laser and Spark Blaster skill damage +7%.",
			"_______________________",
			"When refined to +9 or higher,",
			"increases ranged physical damage by additional 15%.",
			"_______________________",
			"When refined to +10 or higher,",
			"ATK +150.",
			"When equipped by Merchant classes,",
			"STR +50, INT +50.",
			"_______________________",
			"When refined to +11 or higher,",
			"all trait stats +10.",
			"_______________________",
			"When refined to +12 or higher,",
			"increases Triple Laser and Spark Blaster skill damage by additional 15%.",
			"_______________________",
			"When refined to +13 or higher,",
			"increases ranged physical damage by additional 25%.",
			"_______________________",
			"When refined to +14 or higher,",
			"global cooldown -20%, fixed casting time -0.5 sec.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFRobotic Valkyrie Hairband [1]^000000",
			"^4D4DFFRepair Robot Turbo Card^000000",
			"          ",
			"POW +15,",
			"HP and SP recovery +100%,",
			"Global cooldown -20%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 ATK +150.",
			"^4D4DFF[Grade C]^000000 Reduces variable casting time by 20%.",
			"^4D4DFF[Grade B]^000000 MHP and MSP +40%.",
			"^4D4DFF[Grade A]^000000 increases Triple Laser and Spark Blaster skill damage by additional 40%.",
			"_______________________",
			"Type : ^777777Headgear^000000",
			"Defense : ^777777100^000000",
			"Location : ^777777Upper^000000",
			"Weight : ^777777150^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777100^000000",
			"Usable by : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 1405,
		costume = false
	},
	[410652] = {
		unidentifiedDisplayName = "Headgear",
		unidentifiedResourceName = "±Û·¡½º",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Moon Follower Eyepatch",
		identifiedResourceName = "´ÞÀÇ¾È´ë",
		identifiedDescriptionName = {
			"An eyepatch imbued with Hatii's persistence in chasing the moon.",
			"_______________________",
			"MDEF + 20",
			"All Talent Stats + 10.",
			"_______________________",
			"For every 30 sum of pure STR and DEX,",
			"Melee and Ranged physical damage increased by 10%.",
			"_______________________",
			"For every 30 sum of pure INT and DEX,",
			"Magic damage to enemies of all properties increased by 10%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFMoon Follower Eyepatch^000000",
			"^4D4DFFBlue Moon Loli Ruri Egg^000000",
			"     ",
			"Enables the use of Level 1 [Sense].",
			"If intimacy is Loyal:",
			"     ",
			"If pure STR is 120 or higher, POW + 15.",
			"If pure INT is 120 or higher, SPL + 15.",
			"_______________________",
			"Type : ^777777Headgear^000000",
			"Defense : ^77777750^000000",
			"Location : ^777777Middle^000000",
			"Weight : ^77777750^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 1370,
		costume = false
	},
	[420863] = {
		unidentifiedDisplayName = "Von Blood Brothers",
		unidentifiedResourceName = "C_Ghost_Bat_TW",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Von Blood Brothers",
		identifiedResourceName = "C_Ghost_Bat_TW",
		identifiedDescriptionName = {
			"The brothers of Bat von Blood. They gathered and became much stronger.",
			"_______________________",
			"All basic stats + 10",
			"All talent stats + 10",
			"_______________________",
			"ATK +250, MATK +250",
			"_______________________",
			"Restores 777 HP and 77 SP when defeating an enemy using Physical or magical attacks.",
			"_______________________",
			"Enables Greed Lv.1.",
			"_______________________",
			"EXP gained from monsters + 20%.",
			"Item drop rate + 20%.",
			"_______________________",
			"Type : ^777777Headgear^000000",
			"Defense : ^77777720^000000",
			"Location : ^777777Lower^000000",
			"Weight : ^77777720^000000",
			"Required Level : ^7777771^000000",
			"Equipped By : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 2093,
		costume = false,
	},
	[450468] = {
		unidentifiedDisplayName = "Armor",
		unidentifiedResourceName = "¿ìµç¸ÞÀÏ",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Kiel Academy Uniform",
		identifiedResourceName = "ÇÐ»ý±³º¹",
		identifiedDescriptionName = {
			"A neat uniform worn by the students of Kiel Hyre Academy.",
			"_______________________",
			"POW + 5, CON + 5.",
			"_______________________",
			"ATK + 50.",
			"_______________________",
			"When equipped by Expanded Classes, ",
			"MHP + 30000.",
			"EXP Gain from Monster + 50%.",
			"_______________________",
			"For every refine level,",
			"POW + 1, CON + 1, ATK + 10.",
			"_______________________",
			"For every 2 refine level,",
			"STR + 5, DEX + 5, ATK + 20.",
			"_______________________",
			"When refined to +11 or higher,",
			"long-range physical damage + 10%, After Cast Delay - 5%.",
			"_______________________",
			"When refined to +12 or higher,",
			"additional long-range physical damage + 20%, additional After Cast Delay - 10%.",
			"_______________________",
			"When refined to +13 or higher,",
			"All Basic Status + 10, additional long-range physical damage + 30%, additional After Cast Delay - 15%.",
			"_______________________",
			"When refined to +14 or higher,",
			"additional All Basic Status + 15, reduce damage taken from long-range physical attack and damage taken from all size enemies by 30%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFKiel Academy Uniform [1]^000000",
			"^4D4DFFKiel-D-01 Card^000000",
			"          ",
			"All Talent Status + 25.",
			"Increase physical damage against Normal and Boss class enemies by 30%.",
			"Reduce After Cast Delay by 30%.",
			"          ",
			"When Armor Grade is A, reduce Variable Casting Time by 30% and Fixed Casting Time by 1 second.",
			"Enables to use Lv.5 Activate Attack Device.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFKiel Academy Uniform [1]^000000",
			"^4D4DFFAlicel Card^000000",
			"          ",
			"When Armor is refined to +12 or higher, ",
			"Increase long-range physical damage by 30%.",
			"Increase Activate Attack Device damage by 75%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 Ignore physical defense of all class enemies by 20%.",
			"^4D4DFF[Grade C]^000000 Increase melee and long-range physical damage by 15%.",
			"^4D4DFF[Grade B]^000000 Increase Activate Attack Device damage by 75%.",
			"^4D4DFF[Grade A]^000000 When refined to +14 or higher, increase melee and long-range physical damage by 40%.",
			"_______________________",
			"Type : ^777777Armor^000000",
			"Def : ^77777720^000000",
			"Weight : ^77777750^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777100^000000",
			"Class : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[450526] = {
		unidentifiedDisplayName = "Armor",
		unidentifiedResourceName = "ÄÚÆ°¼ÅÃ÷",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Tiara Follower Dress",
		identifiedResourceName = "¿þµùµå·¹½º",
		identifiedDescriptionName = {
			"A long white dress, left behind with lingering regrets, has become the burial shroud of one who wanders forever.",
			"_______________________",
			"MDEF + 15, MATK + 150.",
			"SPL + 10.",
			"_______________________",
			"When equipped by Swordsman, Mage, Acolyte, or Thief classes, MaxHP + 30000, SPL + 10, EXP gained from hunting monsters + 20%.",
			"_______________________",
			"For every 1 refine level,",
			"increase magic damage against all size enemies by 7%.",
			"_______________________",
			"For every 2 refines level,",
			"SPL + 1 and MATK + 20.",
			"_______________________",
			"When refined to +11 or higher,",
			"increase magic damage against all size enemies by 10%, reduce after cast delay by 5%.",
			"_______________________",
			"When refined to +12 or higher,",
			"increase magic damage against all size enemies by 20%, reduce after cast delay by 15%.",
			"_______________________",
			"When refined to +13 or higher,",
			"increase magic damage against all size enemies by 30%, all basic status + 15.",
			"_______________________",
			"When refined to +14 or higher,",
			"all basic stats + 20, reduce damage taken from long-range physical damage by 30%, reduce physical and magic damage from all size enemies by 30%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFTiara Follower Dress [1]^000000",
			"^4D4DFFTiara Card^000000",
			"          ",
			"S.MATK + 40, . increases magical damage against all class enemies by 40%,",
			"If the armor is Grade A or higher, enables to use Lv.5 Crimson Arrow, ignores magical defense of all race enemies by 100%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFTiara Follower Dress [1]^000000",
			"^4D4DFFLord Sakray Card^000000",
			"          ",
			"SPL + 5, all property magic damage + 20%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFTiara Follower Dress [1]^000000",
			"^4D4DFFRestless Dead Card^000000",
			"          ",
			"When refined to + 12 or higher, increase magical damage against all property enemies by 20%, increase Crimson Arrow damage by 30%.",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"^4D4DFF[Grade D]^000000 MATK + 100.",
			"^4D4DFF[Grade C]^000000 Increase All property magic damage by 15%.",
			"^4D4DFF[Grade B]^000000 Reduce Fixed Casting Time by 0.5 seconds.",
			"^4D4DFF[Grade A]^000000 When defeating monsters in the Tomb of Remorse, 30% chance to obtain Mineas.",
			"_______________________",
			"Type : ^777777Armor^000000",
			"Defense : ^777777100^000000",
			"Weight : ^777777100^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777100^000000",
			"Class: ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[450566] = {
		unidentifiedDisplayName = "Armor",
		unidentifiedResourceName = "ÄÚÆ°¼ÅÃ÷",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "November Rain Robe",
		identifiedResourceName = "Imperial_Nature_Robe",
		identifiedDescriptionName = {
			"A robe that marks the end of a long rain and the start of a deep frost.",
			"Pour out your strength without regret, and watch as the world turns white before you.",
			"_______________________",
			"^FF0000Indestructible.^000000",
			"_______________________",
			"MDEF + 15, MaxHP + 20000.",
			"All basic stats + 20.",
			"_______________________",
			"For every 10 Base Levels, increases Crystal Rain damage by 5%.",
			"_______________________",
			"For every 2 refine levels,",
			"increases Water property magic damage by 10%.",
			"_______________________",
			"For every 3 refine levels,",
			"SPL + 5.",
			"_______________________",
			"When refined to +11 or higher,",
			"increases Water property magic damage by an additional 20%.",
			"_______________________",
			"When refined to +12 or higher,",
			"reduces Crystal Rain cooldown by 3 seconds.",
			"_______________________",
			"When refined to +13 or higher,",
			"has a 20% chance to trigger Crystal Rain Lv.5 when using Crystal Rain.",
			"_______________________",
			"When refined to +14 or higher,",
			"has a 10% chance to trigger Frozen Slash Lv.5 when using Crystal Rain.",
			"_______________________",
			"When refined to +15 or higher,",
			"reduces Frozen Slash cooldown by 0.3 seconds and increases Frozen Slash damage by 100%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFNovember Rain Robe [1]^000000",
			"^4D4DFFIce Gangu Card^000000",
			"S.MATK + 5,",
			"     ",
			"Increases Water property magic damage by 25%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFNovember Rain Robe [1]^000000",
			"^4D4DFFIce Straw Card^000000",
			"     ",
			"S.MATK + 5,",
			"Increases Water property magic damage by 25%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFNovember Rain Robe [1]^000000",
			"^4D4DFFStormy Knight Card^000000",
			"     ",
			"MATK + 250,",
			"Increases Water property magic damage by 50%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 Reduces After-cast Delay by 15%.",
			"^4D4DFF[Grade C]^000000 Increase Water property magic damage by 20%.",
			"^4D4DFF[Grade B]^000000 Reduces Crystal Impact cooldown by 1 second.",
			"^4D4DFF[Grade A]^000000 Increases Crystal Impact damage by 50%.",
			"_______________________",
			"Type : ^777777Armor^000000",
			"Def : ^777777100^000000",
			"Weight : ^777777100^000000",
			"Property : ^777777Water^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777100^000000",
			"Class : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[450578] = {
		unidentifiedDisplayName = "Armor",
		unidentifiedResourceName = "ÄÚÆ°¼ÅÃ÷",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Kage Follower Suit",
		identifiedResourceName = "Æ¯¼ö´ÑÀÚ½´Ã÷",
		identifiedDescriptionName = {
			"Suits containing the ambitions of Ninjas who wish to become High Ninjas. Wearing it allows for much faster and deadlier attacks.",
			"_______________________",
			"^FF0000Indestructible.^000000",
			"_______________________",
			"MDEF + 15",
			"MHP + 30%, MSP + 30%.",
			"EXP gained from defeating monsters + 30%.",
			"Reduce After Cast-delay by 15%.",
			"Reduce Variable Casting Time by 15%.",
			"ASPD + 3",
			"_______________________",
			"For every 2 Refine Levels,",
			"STR + 5, INT + 5, MHP + 5%.",
			"_______________________",
			"For every 3 Refine Levels,",
			"POW + 2, SPL + 2.",
			"_______________________",
			"If base INT is 110 or higher,",
			"MATK + 200, SPL + 10,",
			"Damage of Snow Flake Draft, Exploding Dragon, and First Wind increased by 200%.",
			"_______________________",
			"If base STR is 110 or higher,",
			"ATK + 200, POW + 10,",
			"Damage of Throw Huuma Shuriken, Killing Strike, and Swirling Petal increased by 200%.",
			"_______________________",
			"If base SPL is 90 or higher,",
			"MATK + 300, SPL + 15,",
			"Damage of Darkening Cannon, Red Flame Cannon, and Golden Dragon Cannon increased by 200%.",
			"_______________________",
			"If base POW is 90 or higher,",
			"ATK + 300, POW + 15,",
			"Damage of Shadow Dance and Kunai-Rotation increased by 200%.",
			"_______________________",
			"When refine level is +10 or higher,",
			"For every 2 Base Levels, increased damage of Exploding Dragon and Throw Huuma Shuriken by 1%.",
			"_______________________",
			"When refine level is +11 or higher,",
			"Enables to use Lv 5 Hallucination Walk, reduce Hallucination Walk Cooldown by 180 seconds.",
			"_______________________",
			"When refine level is +12 or higher,",
			"POW + 20, SPL + 20.",
			"_______________________",
			"When refine level is +13 or higher,",
			"Enables to use Lv 5 Vituperatum, reduce Vituperatum Cooldown by 4 seconds.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFKage Follower Suit [1]^000000",
			"^4D4DFFAsh Toad Card^000000",
			"          ",
			"SPL + 10, increase Earth property magic damage by 35%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFKage Follower Suit [1]^000000",
			"^4D4DFFLava Toad Card^000000",
			"          ",
			"SPL + 10, Fire property magic damage + 35%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFKage Follower Suit [1]^000000",
			"^4D4DFFFaceworm Dark Card^000000",
			"          ",
			"POW + 10, Physical damage to all size enemies + 20%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 ATK + 150, MATK + 150.",
			"^4D4DFF[Grade C]^000000 Physical/Magic damage to all size enemies + 20%.",
			"^4D4DFF[Grade B]^000000 Reduces After-cast Delay by 15%.",
			"^4D4DFF[Grade A]^000000 When using Skill Ninja Aura, All basic stats + 60, Perfect Dodge + 60 for 30 seconds.",
			"_______________________",
			"Type : ^777777Armor^000000",
			"Defense : ^777777100^000000",
			"Weight : ^777777100^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^7777771^000000",
			"Jobs : ^777777Ninja Classes^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[460108] = {
		unidentifiedDisplayName = "Shield",
		unidentifiedResourceName = "°¡µå",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Doram Shield-LT",
		identifiedResourceName = "Doram_Shield",
		identifiedDescriptionName = {
			"A shield said to have been left behind by the legendary Doram.",
			"_______________________",
			"^FF0000Indestructible.^000000",
			"_______________________",
			"ATK +50, MATK +50.",
			"_______________________",
			"For every 2 upgrade levels:",
			"ATK +15, MATK +15.",
			"_______________________",
			"If upgrade level is +7 or higher:",
			"ASPD +10%, MaxHP +5%.",
			"_______________________",
			"If upgrade level is +9 or higher:",
			"Reduces after-cast delay by 10%.",
			"Additional MaxHP +5%.",
			"_______________________",
			"If upgrade level is +11 or higher:",
			"Reduces Howling of Chulho cooldown by 0.5 seconds.",
			"Reduces Hyunrok Breeze cooldown by 1.5 seconds.",
			"_______________________",
			"If upgrade level is +12 or higher:",
			"Increases Howling of Chulho and Hyunrok Breeze damage by 10%.",
			"_______________________",
			"[Bonus by Grade]",
			"[Grade D]: Increases long-ranged physical damage by 10%. Increases magic damage of all property by 10%.",
			"[Grade C]: Increases Howling of Chulho and Hyunrok Breeze damage by an additional 10%.",
			"[Grade B]: Increases Hogogong Strike and Hyunrok Cannon damage by 15%.",
			"[Grade A]: Increases physical and magic damage against all size enemies by 20%. MaxHP +5000.",
			"_______________________",
			"Type : ^777777Shield^000000",
			"Defense : ^77777740^000000",
			"Weight : ^77777730^000000",
			"Armor Level : ^7777772^000000",
			"_______________________",
			"^0000CCRequirement:^000000",
			"Base Level 200",
			"Spirit Handler"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[470443] = {
		unidentifiedDisplayName = "Shoes",
		unidentifiedResourceName = "ºÎÃ÷",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Heretic Acolyte Boots",
		identifiedResourceName = "Dimension_H_Boots",
		identifiedDescriptionName = {
			"A pair of boots worn by an acolyte who wandered into forbidden faith.",
			"_______________________",
			"MDEF + 10.",
			"_______________________",
			"All Basic Status + 15.",
			"_______________________",
			"All Talent Status + 15.",
			"_______________________",
			"MHP + 20%, MSP + 20%.",
			"_______________________",
			"For every 20 Base Levels,",
			"ATK + 70, MATK + 70.",
			"_______________________",
			"For every 2 refine levels,",
			"Adoramus and Tiger Cannon damage + 30%.",
			"_______________________",
			"For every 3 refine level,",
			"POW + 5, SPL + 5, WIS + 5.",
			"_______________________",
			"When refined to +11 or higher,",
			"reduces Tiger Cannon cooldown by 3 sec, reduces Adoramus cooldown by 2.5 sec.",
			"_______________________",
			"When refined to +12 or higher,",
			"Adoramus and Tiger Cannon damage + 70%, enables use of Energy Coat Lv.1.",
			"_______________________",
			"When refined to +13 or higher,",
			"Flamen and Explosion Blaster damage + 70%, reduces Fixed Casting Time by 1 sec.",
			"_______________________",
			"When refined to +14 or higher,",
			"SPL + 20, POW + 20, reduces After Cast Delay by 30%.",
			"_______________________",
			"When refined to +15 or higher,",
			"increases physical and magic damage against all property enemies by 50%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFHeretic Acolyte Boots [1]^000000",
			"^4D4DFFRechenier Card^000000",
			"          ",
			"S.MATK + 15, Flamen damage + 50%.",
			"Reduces Flamen cooldown by 0.2 sec.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFHeretic Acolyte Boots [1]^000000",
			"^4D4DFFPa Monk Card^000000",
			"          ",
			"P.ATK + 15, Explosion Blaster damage + 50%.",
			"Reduces Explosion Blaster cooldown by 0.6 sec.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFHeretic Acolyte Boots [1]^000000",
			"^4D4DFFMidnight Licheniyes Card^000000",
			"          ",
			"S.MATK + 30, SPL + 30.",
			"Flamen damage + 100%.",
			"Reduces Flamen cooldown by 0.3 sec.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFHeretic Acolyte Boots [1]^000000",
			"^4D4DFFMidnight Faymont Card^000000",
			"          ",
			"P.ATK + 30, POW + 30.",
			"Explosion Blaster damage + 100%.",
			"Reduces Explosion Blaster cooldown by 0.7 sec.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFHeretic Acolyte Boots [1]^000000",
			"^4D4DFFWeakened Fenrir Card^000000",
			"          ",
			"P.ATK + 15, S.MATK + 15.",
			"Reduces After Cast Delay by 15%.",
			"Increases physical and magic damage against all size enemies by 15%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 When equipped by Cardinal, enables use of Explosion Blaster Lv.5. When equipped by Inquisitor, enables use of Flamen Lv.5.",
			"^4D4DFF[Grade C]^000000 When using Energy Coat, increases movement speed, STR + 100, INT + 100 for 10 seconds.",
			"^4D4DFF[Grade B]^000000 Increases physical and magic damage against all race enemies (including player) by 25%.",
			"^4D4DFF[Grade A]^000000 Removes Gemstone requirements for skill usage.",
			"_______________________",
			"Type : ^777777Shoes^000000",
			"Defense : ^77777750^000000",
			"Weight : ^77777730^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777100^000000",
			"Class : ^777777Acolyte^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[480539] = {
		unidentifiedDisplayName = "Garment",
		unidentifiedResourceName = "¸®º»",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Royal Nightwatch Cape",
		identifiedResourceName = "C_H_Knight_Cloak",
		identifiedDescriptionName = {
			"A cloak worn by the Nightwatch.",
			"_______________________",
			"Immune to Knockback.",
			"_______________________",
			"Increase long-range physical damage by 20%.",
			"_______________________",
			"For every 2 refine level,",
			"ATK + 20, CON + 4.",
			"_______________________",
			"For every 3 refine level,",
			"increase long-range physical damage and physical damage against all size enemies by 7%.",
			"_______________________",
			"When refined to +7 or higher,",
			"ASPD + 10%, increase long-range physical damage by 15%.",
			"_______________________",
			"When refined to +9 or higher,",
			"increase physical damage against all property enemies by 20%.",
			"_______________________",
			"When refined to +10 or higher,",
			"ATK + 100.",
			"_______________________",
			"When refined to +11 or higher,",
			"All Basic Status + 15.",
			"_______________________",
			"When refined to +12 or higher,",
			"CON + 10, increase long-range physical damage by 15%.",
			"_______________________",
			"When refined to +13 or higher,",
			"increase Round Trip, Fire Dance, and Vanishing Buster damage by 100%.",
			"_______________________",
			"When refined to +14 or higher,",
			"enables to use Lv.3 Shield Spell.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFRoyal Nightwatch Cape [1]^000000",
			"^4D4DFFTurtle General Card^000000",
			"          ",
			"Increase physical damage against Boss class enemies by 40%.",
			"          ",
			"When garment is refined to +14 or higher,",
			"there's a 5% chance to gain STR + 250, DEX + 250, LUK + 250 for 10 seconds when dealing melee or long-range physical attack.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFRoyal Nightwatch Cape [1]^000000",
			"^4D4DFFCowraiders Class 1 Card^000000",
			"          ",
			"MHP + 15%.",
			"Increase long-range physical damage by 20%.",
			"Increase Vanishing Buster damage by 30%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFRoyal Nightwatch Cape [1]^000000",
			"^4D4DFFCowraiders Class 2 Card^000000",
			"          ",
			"MHP + 15%.",
			"Increase long-range physical damage by 20%.",
			"Increase Fire Dance damage by 30%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 ATK + 50.",
			"^4D4DFF[Grade C]^000000 Reduce After Cast Delay by 15%.",
			"^4D4DFF[Grade B]^000000 P.ATK + 10.",
			"^4D4DFF[Grade A]^000000 When refined to +15 or higher, long-range physical damage + 40%.",
			"_______________________",
			"Type : ^777777Garment^000000",
			"Def : ^7777770^000000",
			"Weight : ^77777710^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777100^000000",
			"Class : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[490617] = {
		unidentifiedDisplayName = "Accessory",
		unidentifiedResourceName = "Å¬¸³",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Dictator Bracelet",
		identifiedResourceName = "Jade_Emperors_Bracelet",
		identifiedDescriptionName = {
			"A bracelet used to symbolize the power held by Caesar of the Ancient Rome.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFDictator Bracelet [1]^000000",
			"^4D4DFFDiana Suit-LT [1]^000000",
			"          ",
			"Increase physical and magic damage against all size enemies by 8%.",
			"Increase Hogogong Strike and Hyunrok Breeze damage by 10%.",
			"          ",
			"When ^4D4DFFArmor Grade is A^000000,",
			"increase Hogogong Strike and Hyunrok Breeze damage by additional 10%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFDictator Bracelet [1]^000000",
			"^4D4DFFBacchus Armor-LT [1]^000000",
			"          ",
			"Increase physical damage against all size enemies by 10%.",
			"Increase Only One Bullet and Magazine for One damage by 10%.",
			"          ",
			"When ^4D4DFFArmor Grade is A^000000,",
			"increase Only One Bullet and Magazine for One damage by additional 10%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFDictator Bracelet [1]^000000",
			"^4D4DFFMercury Suit-LT [1]^000000",
			"          ",
			"Increase physical and magic damage against all size enemies by 8%.",
			"Increase Darkening Cannon and Shadow Flash damage by 10%.",
			"          ",
			"When ^4D4DFFArmor Grade is A^000000,",
			"increase Darkening Cannon and Shadow Flash damage by additional 10%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFDictator Bracelet [1]^000000",
			"^4D4DFFNeptune Uniform-LT [1]^000000",
			"          ",
			"Increase physical and magic damage against all size enemies by 8%.",
			"Increase Midnight Kick and Exorcism of Malicious Soul damage by 10%.",
			"          ",
			"When ^4D4DFFArmor Grade is A^000000,",
			"increase Midnight Kick and Exorcism of Malicious Soul damage by additional 10%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFDictator Bracelet [1]^000000",
			"^4D4DFFJanus Armor-LT [1]^000000",
			"          ",
			"Increase physical and magic damage against all size enemies by 8%.",
			"Increase Napalm Vulcan Strike and Double Bowling Bash damage by 10%.",
			"          ",
			"When ^4D4DFFArmor Grade is A^000000,",
			"increase Napalm Vulcan Strike and Double Bowling Bash damage by additional 10%.",
			"_______________________",
			"Type : ^777777Accessory^000000",
			"Def : ^7777770^000000",
			"Weight : ^77777710^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777205^000000",
			"Class : ^7777774th Expanded Job^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[480823] = {
		unidentifiedDisplayName = "Garment",
		unidentifiedResourceName = "ÈÄµå",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Abysmal Follower Cape",
		identifiedResourceName = "Scorpio_Manteau_J",
		identifiedDescriptionName = {
			"At the bottom of the abyss, the world's ancient heat breaks through the crushing weight of the sea.",
			"_______________________",
			"^FF0000Indestructible.^000000",
			"_______________________",
			"MDEF + 15.",
			"All basic stats + 10.",
			"All talent stats + 10.",
			"MHP + 20%, MSP + 20%.",
			"_______________________",
			"For every 10 Base Levels,",
			"MATK + 50.",
			"_______________________",
			"For every 2 refine levels,",
			"increases magic damage to enemies of all properties by 10%.",
			"_______________________",
			"For every 3 refine levels,",
			"SPL + 4, CON + 4, WIS + 4.",
			"_______________________",
			"When refined to +11 or higher,",
			"increases All Bloom and Mystery Illusion damage by 40%.",
			"_______________________",
			"When refined to +12 or higher,",
			"reduces All Bloom cooldown by 5.5 seconds and Mystery Illusion cooldown by 3.5 seconds.",
			"_______________________",
			"When refined to +13 or higher,",
			"increases magic damage to enemies of all properties by 20%.",
			"_______________________",
			"When refined to +14 or higher,",
			"SPL + 15, reduces After-cast Delay by 30%.",
			"_______________________",
			"When refined to +15 or higher,",
			"increases magic damage to enemies of all properties by 40%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFAbysmal Follower Cape [1]^000000",
			"^4D4DFFAbysmal Witch Card^000000",
			"     ",
			"S.MATK + 30, CON + 30,",
			"Increases magic damage to Normal and Boss Monster by 40%,",
			"When dealing physical or magic attacks, has a 7% chance to grant SPL + 150 for 7 seconds.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFAbysmal Follower Cape [1]^000000",
			"^4D4DFFAbysmal Strouf Card^000000",
			"     ",
			"Immunity to Knockback,",
			"Increase Fire and Shadow property magic damage by 30%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFAbysmal Follower Cape [1]^000000",
			"^4D4DFFAbysmal Deviace Card^000000",
			"     ",
			"MATK + 250,",
			"Increase Fire property magic damage by 30%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFAbyssmal Follower Cape [1]^000000",
			"^4D4DFFAbysmal Sropho Card^000000",
			"     ",
			"MATK + 250,",
			"Increase Shadow property magic damage by 30%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 Reduces Fixed Casting Time by 0.5 seconds.",
			"^4D4DFF[Grade C]^000000 Increase Fire and Shadow property magic damage by 30%.",
			"^4D4DFF[Grade B]^000000 Increases magic damage to enemies of all races by 20%.",
			"^4D4DFF[Grade A]^000000 Increases All Bloom and Mystery Illusion damage by 100%.",
			"_______________________",
			"Type : ^777777Garment^000000",
			"Def : ^777777100^000000",
			"Weight : ^777777100^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777100^000000",
			"Class : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[490836] = {
		unidentifiedDisplayName = "Accessorry (right)",
		unidentifiedResourceName = "³×Å¬¸®½º",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Chaos Necklace",
		identifiedResourceName = "³«¿ø´Ü¸ñ°ÉÀÌ2",
		identifiedDescriptionName = {
			"Within this amulet swirls the distilled core of disorder.",
			"To wear it is to invite both brilliance and ruin in equal measure.",
			"_______________________",
			"ATK + 70.",
			"_______________________",
			"All Talent Status + 7.",
			"_______________________",
			"Reduces After Cast Delay by 15%.",
			"_______________________",
			"Increases physical damage against all sizes by 20%.",
			"_______________________",
			"When Base Level is below 100,",
			"MHP + 10000, MSP + 2000.",
			"Reduces damage taken from Demi-human enemies (including Players) by 20%.",
			"Reduces damage taken from Medium-sized enemies by 20%.",
			"Reduces fixed casting time by 0.3 seconds.",
			"Increases Bowling Bash damage by 150%.",
			"_______________________",
			"When Base Level is 100 or higher,",
			"POW + 7, CRT + 7, CON + 7.",
			"For every 6 Base Levels, increases physical damage against all sizes by 1%.",
			"For every 10 Base Levels, increases Hack and Slash and Storm Slash damage by 2%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFChaos Necklace [1]^000000",
			"^4D4DFFChaos Sword [2]^000000",
			"          ",
			"Reduces Hack and Slash cooldown by 0.5 seconds.",
			"Increases physical damage against all sizes by 30%.",
			"When weapon is refined to +14 or higher, auto-casts Storm Slash Lv.5 when using Hack and Slash.",
			"_______________________",
			"Type : ^777777Accessory (Right)^000000",
			"Def : ^77777750^000000",
			"Weight : ^77777750^000000",
			"Armor Level : ^7777771^000000",
			"Required Level : ^7777771^000000",
			"Class : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[490866] = {
		unidentifiedDisplayName = "Accessory",
		unidentifiedResourceName = "Å¬¸³",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Celine's Brooch-LT",
		identifiedResourceName = "Celine_Brooch_LT",
		identifiedDescriptionName = {
			"A high quality brooch that is made by one of the best craftsman in the world. It has been together with Celine since she was created.",
			"_______________________",
			"MATK + 10%.",
			"MHP + 3000, MSP + 500.",
			"Reduces variable casting time by 30%.",
			"ASPD + 2.",
			"_______________________",
			"When refined to +7 or higher,",
			"reduces after-cast delay by 7%.",
			"_______________________",
			"When refined to +13 or higher,",
			"increases magic damage against enemies of all properties by 10%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFCeline Brooch-LT [1]^000000",
			"^4D4DFFEvil Spirit Glove [1]^000000",
			" ",
			"ATK + 250, MATK + 250.",
			"Adds a 7% chance to cast Level 10 Varetyr Spear and Level 5 Earth Grave on the enemy when dealing physical attacks.",
			"Adds a 1% chance to cast Level 1 Recognized Spell on yourself when dealing magic attacks.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFCeline Brooch-LT [1]^000000",
			"^4D4DFFCeline's Ribbon [1]^000000",
			" ",
			"Reduces fixed casting time by 70%,",
			"reduces damage taken from all races by 12%,",
			"for every 3 refine levels of the headgear, increases magic damage against Boss monsters by 20%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFCeline Brooch-LT [1]^000000",
			"^4D4DFFBloody Celine Dress-LT [1]^000000",
			" ",
			"MATK + 200,",
			"increases magic damage of all properties by 10%,",
			"increases magic damage against enemies of all properties by 35%,",
			"adds a 5% chance to cast Level 5 Soul Expansion and Level 4 Soul Vulcan Strike on the enemy when dealing physical attacks.",
			"Adds a 1% chance to cast Level 4 Intensification on yourself when dealing magic attacks.",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"^4D4DFF[Grade D]^000000 Enables to use Recognized Spell Lv. 3 (Buff is removed when unequipped).",
			"^4D4DFF[Grade C]^000000 Increases magic damage of all properties by 10%.",
			"^4D4DFF[Grade B]^000000 SPL + 5.",
			"^4D4DFF[Grade A]^000000 Increases magic damage against Boss monsters by 10%.",
			"_______________________",
			"Type : ^777777Accessory^000000",
			"Def : ^7777770^000000",
			"Weight : ^77777750^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777150^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[490867] = {
		unidentifiedDisplayName = "Accessory",
		unidentifiedResourceName = "Å¬¸³",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Celine Kimi Pendant-LT",
		identifiedResourceName = "Cel_Design_Pendant_LT",
		identifiedDescriptionName = {
			"A pendant decorated with cute Celine Kimi.",
			"_______________________",
			"Increases magic damage of all properties by 15%, SPL + 5.",
			"_______________________",
			"When refined to +7 or higher,",
			"reduces after-cast delay by 7%.",
			"_______________________",
			"When refined to +13 or higher,",
			"increases magic damage against enemies of all sizes by 12%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFCeline Kimi Pendant-LT [1]^000000",
			"^4D4DFFCeline's Ribbon [1]^000000",
			" ",
			"Increases magic damage against enemies of all races by 25%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFCeline Kimi Pendant-LT [1]^000000",
			"^4D4DFFCeline's Brooch-LT [1]^000000",
			" ",
			"Increases Shadow property magic damage by 20%,",
			"adds a 3% chance to cast Level 4 Mystery Illusion and Level 8 Darkening Cannon on the enemy when dealing physical attacks.",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"^4D4DFF[Grade D]^000000 MATK + 8%.",
			"^4D4DFF[Grade C]^000000 Increases magic damage against enemies of all properties by 10%.",
			"^4D4DFF[Grade B]^000000 SPL + 5.",
			"^4D4DFF[Grade A]^000000 Increases magic damage against Boss monsters by 10%.",
			"_______________________",
			"Type : ^777777Accessory^000000",
			"Def : ^7777770^000000",
			"Weight : ^77777710^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777150^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[490927] = {
		unidentifiedDisplayName = "Necklace",
		unidentifiedResourceName = "³×Å¬¸®½º",
		unidentifiedDescriptionName = { "Unidentified item, please use [Magnifier] to identify." },
		identifiedDisplayName = "Royal Necklace",
		identifiedResourceName = "Shine_Necklace_R",
		identifiedDescriptionName = {
			"A brilliantly shining Royal Necklace adorned with a red ruby.",
			"Created as a set with the Royal Cape or Muffler, Pair this with the cape for a more elegant look.",
			"_______________________",
			"MDEF + 15.",
			"     ",
			"ATK + 100, MATK + 100.",
			"     ",
			"All Basic Stats + 10.",
			"     ",
			"All Talent Stats + 10.",
			"     ",
			"Reduces After-cast Delay by 10%.",
			"     ",
			"Increases Physical and Magical Damage against all sizes enemies by 10%.",
			"_______________________",
			"For every 5 Base Levels,",
			"increase Physical and Magical Damage against all size enemies by an additional 1%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFRoyal Necklace [1]^000000",
			"^4D4DFFRoyal Prontera Cape [1]^000000",
			"OR",
			"^4D4DFFRoyal Payon Cape [1]^000000",
			"^4D4DFFRoyal Geffen Cape [1]^000000",
			"^4D4DFFRoyal Alberta Cape [1]^000000",
			"^4D4DFFRoyal Morroc Cape [1]^000000",
			"^4D4DFFRoyal Moscovia Cape [1]^000000",
			"^4D4DFFRoyal Nightwatch Cape [1]^000000",
			"^4D4DFFRoyal Dragon Cape [1]^000000",
			"^4D4DFFRoyal Monastery Muffler [1]^000000",
			"     ",
			"ATK + 150, MATK + 150.",
			"All Basic Stats + 10.",
			"All Talent Stats + 10.",
			"Reduce After-cast Delay by 15%.",
			"     ",
			"For every 1 refine level of the garment,",
			"increase Physical and Magical Damage against all size enemies by 7%.",
			"_______________________",
			"Type : ^777777Accessory (Right)^000000",
			"Def : ^777777150^000000",
			"Weight : ^777777100^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[491013] = {
		unidentifiedDisplayName = "Accessory (Right)",
		unidentifiedResourceName = "³×Å¬¸®½º",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Spin Ball",
		identifiedResourceName = "Lightning_Cannon_Ball",
		identifiedDescriptionName = {
			"A floating orb that enhances the wearer's rotational force.",
			"_______________________",
			"^FF0000Indestructible.^000000",
			"_______________________",
			"POW + 15, CON + 15.",
			"Perfect Dodge + 50.",
			"     ",
			"Increases Wind Cutter damage by 50%.",
			"_______________________",
			"For every 2 refine levels,",
			"POW + 3, CON + 3.",
			"_______________________",
			"When refined to +7 or higher,",
			"reduces Variable Casting Time by 15% and After-cast Delay by 15%.",
			"_______________________",
			"When refined to +8 or higher,",
			"increase physical damage to enemies of all sizes by 20%, increases Rolling Cutter damage by 50%.",
			"_______________________",
			"When refined to +9 or higher,",
			"reduces After-cast Delay by an additional 15%, increases Axe Tornado damage by 50%.",
			"_______________________",
			"When refined to +10 or higher,",
			"increase physical damage to enemies of all properties by 25%, increases Cart Tornado damage by 50%.",
			"_______________________",
			"When refined to +11 or higher,",
			"POW + 8, CON + 8.",
			"_______________________",
			"When refined to +12 or higher,",
			"     ",
			"Has an 80% chance to trigger Rolling Cutter Lv.5 when using Rolling Cutter.",
			"Has an 80% chance to trigger Axe Tornado Lv.5 when using Axe Tornado.",
			"Has an 80% chance to trigger Cart Tornado Lv.10 when using Cart Tornado.",
			"_______________________",
			"When refined to +13 or higher,",
			"Has a 40% chance to trigger Wind Cutter Lv.5 when using Rolling Cutter, Axe Tornado, or Cart Tornado.",
			"_______________________",
			"When refined to +14 or higher,",
			"increases Wind Cutter damage by 120%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFSpin Ball [1]^000000",
			"^4D4DFFEremes Guile Card^000000",
			"     ",
			"POW + 7,",
			"Increases Rolling Cutter damage by 70%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFSpin Ball [1]^000000",
			"^4D4DFFHoward Alt-Eisen Card^000000",
			"     ",
			"POW + 5,",
			"Increases Axe Tornado and Cart Tornado damage by 50%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFSpin Ball [1]^000000",
			"^4D4DFFBoss Egnigem Card^000000",
			"     ",
			"POW + 30,",
			"Increases physical damage to Normal and Boss enemies by 40%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 Increases physical damage to enemies of all sizes by 30%.",
			"^4D4DFF[Grade C]^000000 All talent stats + 10.",
			"^4D4DFF[Grade B]^000000 Increases Wind Cutter damage by 150%.",
			"_______________________",
			"Type : ^777777Accessory (Right)^000000",
			"Def : ^77777750^000000",
			"Weight : ^777777100^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777100^000000",
			"Class : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[491053] = {
		unidentifiedDisplayName = "Accessory (Left)",
		unidentifiedResourceName = "¸µ",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Focused Love Ring",
		identifiedResourceName = "Leo_Ring_J",
		identifiedDescriptionName = {
			"A ring that has become even more special over a long period of time. Unwavering love has changed the ring's appearance.",
			"_______________________",
			"MHP + 30%, MSP + 30%.",
			"     ",
			"Increase Physical and magical damage to all size enemies by 30%.",
			"     ",
			"EXP gained from monsters + 20%.",
			"Item drop rate + 15%.",
			"_______________________",
			"Type : ^777777Accessory (Left)^000000",
			"Defense : ^7777770^000000",
			"Weight : ^7777770^000000",
			"Required Level : ^7777771^000000",
			"Equipped By : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[491054] = {
		unidentifiedDisplayName = "Accessory (Right)",
		unidentifiedResourceName = "¸µ",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Focused Hatred Ring",
		identifiedResourceName = "³«¿ø´Ü¹ÝÁö",
		identifiedDescriptionName = {
			"A ring whose appearance has been transformed by deep hatred. ",
			"_______________________",
			"MHP + 30%, MSP + 30%.",
			"     ",
			"Increase Physical and magical damage to all size enemies by 30%.",
			"     ",
			"EXP gained from monsters + 20%.",
			"Item drop rate + 15%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFFocused Hatred Ring [1]^000000",
			"^4D4DFFFocused Love Ring [1]^000000",
			"     ",
			"All basic stats + 15,",
			"All talent stats + 15,",
			"Increased movement speed, Item drop rate + 25%.",
			"_______________________",
			"Type : ^777777Accessory (Right)^000000",
			"Defense : ^7777770^000000",
			"Weight : ^77777710^000000",
			"Required Level : ^7777771^000000",
			"Equipped By : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[491057] = {
		unidentifiedDisplayName = "Accessory (Left)",
		unidentifiedResourceName = "¸µ",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Purple Haze",
		identifiedResourceName = "Poison_Stone_4th",
		identifiedDescriptionName = {
			"A stone imbued with a dreamy yet potent poisonous aura.",
			"_______________________",
			"Drains 666 HP from user every 5 seconds.",
			"_______________________",
			"MDEF + 25.",
			"_______________________",
			"POW + 15, SPL + 15.",
			"_______________________",
			"Cross Impact and Fatal Menace damage + 50%.",
			"_______________________",
			"When using Reproduce or Weapon Blocking, increases movement speed, P.ATK + 20, S.MATK + 20 for 20 seconds.",
			"_______________________",
			"For every 2 refine levels,",
			"POW + 3, SPL + 3.",
			"_______________________",
			"When refined +8 or higher,",
			"reduces Variable Casting Time by 15%, reduces After Cast Delay by 15%, ASPD + 3.",
			"_______________________",
			"When refined +9 or higher,",
			"physical and magic damage to all size enemies + 20%, Poison property magic damage + 20%, Cross Impact and Fatal Menace damage + 50%.",
			"_______________________",
			"When refined +10 or higher,",
			"when using Cross Impact or Fatal Menace, 60% chance to auto-cast Poison Burst Lv.5.",
			"_______________________",
			"When refined +11 or higher,",
			"when performing physical attack or receiving melee physical attack, 10% chance to auto-cast Venom Swamp Lv.5.",
			"_______________________",
			"When refined +12 or higher,",
			"POW + 8, SPL + 8, when using Venom Swamp, auto-cast Killing Cloud Lv.5.",
			"_______________________",
			"When refined +13 or higher,",
			"physical and magic damage to all property enemies + 30%, Poison property magic damage + 30%.",
			"_______________________",
			"When refined +14 or higher,",
			"Cross Impact and Fatal Menace damage + 70%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFPurple Haze [1]^000000",
			"^4D4DFFVenedi Card^000000",
			"          ",
			"SPL + 10, Poison property magic damage + 30%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFPurple Haze [1]^000000",
			"^4D4DFFVenenum Card^000000",
			"          ",
			"POW + 10, physical damage to all size enemies + 30%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFPurple Haze [1]^000000",
			"^4D4DFFPowerful Amdarais Card^000000",
			"          ",
			"POW + 15, SPL + 15,",
			"Physical and magic damage to Boss and Normal enemies + 30%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 Physical and magic damage to all size enemies + 30%.",
			"^4D4DFF[Grade C]^000000 All Talent Status + 10.",
			"^4D4DFF[Grade B]^000000 P.ATK + 15, S.MATK + 15.",
			"^4D4DFF[Grade A]^000000 Poison Burst and Venom Swamp damage + 100%.",
			"_______________________",
			"Type : ^777777Accessory (Left)^000000",
			"Defense : ^7777770^000000",
			"Weight : ^77777750^000000",
			"Armor Level : ^7777772^000000",
			"Required Level : ^777777100^000000",
			"Class : ^777777Thief, Ninja^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[510222] = {
		unidentifiedDisplayName = "Dagger",
		unidentifiedResourceName = "³ªÀÌÇÁ",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Blood Ruby Dagger",
		identifiedResourceName = "RightShape_Furious",
		identifiedDescriptionName = {
			"A cursed dagger infused with a blood ruby that restores its wielder's vitality with every strike.",
			"_______________________",
			"MATK + 250.",
			"_______________________",
			"Enables use of Crimson Rock Lv.5.",
			"_______________________",
			"When dealing physical damage,",
			"has a 50% chance to absorb 2% of the damage dealt as HP.",
			"_______________________",
			"Crimson Rock, Dragon's Breath, and Cart Cannon damage + 50%.",
			"_______________________",
			"Damage received from Normal class enemies - 30%.",
			"_______________________",
			"For every refine level,",
			"Crimson Rock, Dragon's Breath, and Cart Cannon damage + 15%.",
			"_______________________",
			"When refined to +11 or higher,",
			"MHP + 20%, MSP + 20%.",
			"_______________________",
			"When refined to +12 or higher,",
			"All Basic Status + 20, ATK + 200, MATK + 200, when dealing melee physical damage, has a 7% chance to autocast Crimson Rock Lv. 5.",
			"_______________________",
			"When refined to +13 or higher,",
			"P.ATK + 15, S.MATK + 15, Crimson Rock cooldown - 4.8 sec, Fixed cast time - 0.5 sec.",
			"_______________________",
			"When refined to +14 or higher,",
			"P.ATK + 15, S.MATK + 15.",
			"_______________________",
			"When refined to +15 or higher,",
			"Long-ranged physical damage + 40%, Fire property magic damage + 40%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFBlood Ruby Dagger [2]^000000",
			"^4D4DFFAmdarais Card^000000",
			"          ",
			"POW + 20, SPL + 20, CON + 20,",
			"Physical and magic damage against all race enemies + 20%,",
			"Enables use of No Limits Lv. 1.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFBlood Ruby Dagger [2]^000000",
			"^4D4DFFAmdarais H Card^000000",
			"          ",
			"POW + 30, SPL + 30, CON + 30,",
			"Physical and magic damage against all race enemies + 30%,",
			"Enables use of No Limits Lv. 2.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFBlood Ruby Dagger [2]^000000",
			"^4D4DFFBurning Fang Card^000000",
			"          ",
			"S.MATK + 25, Fire property magic damage + 75%,",
			"When receiving physical damage, has a 10% chance to autocast Crimson Rock Lv. 5.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFBlood Ruby Dagger [2]^000000",
			"^4D4DFFBanaspaty Card^000000",
			"          ",
			"SPL + 7, POW + 7, ",
			"Physical and magic damage against all race enemies + 12%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 All Basic Status + 15.",
			"^4D4DFF[Grade C]^000000 Long-ranged physical damage + 20%, Fire property magic damage + 20%.",
			"^4D4DFF[Grade B]^000000 Physical and magic damage against all race enemies (including player) + 20%.",
			"^4D4DFF[Grade A]^000000 Grants Endure effect.",
			"_______________________",
			"Type : ^777777Dagger^000000",
			"Attack : ^777777250^000000",
			"Weight : ^77777770^000000",
			"Weapon Level : ^7777775^000000",
			"Required Level : ^777777100^000000",
			"Class : ^777777Swordman, Archer, Thief, Mage, Merchant, Ninja, and Soul Linker Classes^000000"
		},
		slotCount = 2,
		ClassNum = 31,
		costume = false
	},
	[520062] = {
		unidentifiedDisplayName = "Axe",
		unidentifiedResourceName = "¾×½º",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Thorn Breaker",
		identifiedResourceName = "Melon_T_Axe",
		identifiedDescriptionName = {
			"Grants the weapon with Earth Property.",
			"_______________________",
			"^FF0000Indestructible.^000000",
			"_______________________",
			"ATK + 250, MATK + 250.",
			"Enables to use Lv 5 Explosive Powder.",
			"Damage of Mayhemic Thorns and Explosive Powder increased by 50%.",
			"When performing physical attacks, has a 100% chance to absorb 2% of the damage dealt as HP, and a 5% chance to inflict Stun on the enemy.",
			"_______________________",
			"For every refine level,",
			"damage of Mayhemic Thorns and Explosive Powder increased by an additional 12%.",
			"_______________________",
			"When refine level is +11 or higher,",
			"MHP + 25%, MSP + 25%, reduces damage taken from normal monsters by 25%.",
			"_______________________",
			"When refine level is +12 or higher,",
			"ATK + 200, MATK + 200, all basic stats + 20.",
			"_______________________",
			"When refine level is +13 or higher,",
			"Ranged physical damage + 20%, damage of Mayhemic Thorns and Explosive Powder increased by an additional 70%.",
			"_______________________",
			"When refine level is +14 or higher,",
			"POW + 15, CON + 15, Ranged physical damage increased by an additional 30%, reduce Mayhemic Thorns Cooldown by 0.5 seconds.",
			"_______________________",
			"When refine level is +15 or higher,",
			"Physical damage to normal and boss monster increased by 40%, reduces After-cast Delay by 30%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFThorn Breaker [3]^000000",
			"^4D4DFFTendrilion Card^000000",
			"      ",
			"POW + 12.",
			"Enables the use of Level 5 Earth Shaker.",
			"Damage of Earth Shaker increased by 70%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFThorn Breaker [3]^000000",
			"^4D4DFFGreater Special Alnoldi Card^000000",
			"      ",
			"POW + 12.",
			"Enables the use of Level 10 Crazy Vines.",
			"Damage of Crazy Vines increased by 70%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFThorn Breaker [3]^000000",
			"^4D4DFFNepenthes Card^000000",
			"      ",
			"POW + 12.",
			"Enables the use of Level 5 Hell Plant.",
			"Damage of Hell Plant increased by 70%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFThorn Breaker [3]^000000",
			"^4D4DFFLady Tanee Card^000000",
			"      ",
			"POW + 30, CON + 30.",
			"Physical damage to normal and boss monster increased by 50%.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 P.ATK + 25.",
			"^4D4DFF[Grade C]^000000 Reduces After-cast Delay by 20%.",
			"^4D4DFF[Grade B]^000000 Ignores 75% physical defense of all races (Including Players).",
			"^4D4DFF[Grade A]^000000 All basic stats + 12, all talent stats + 12.",
			"_______________________",
			"Type : ^777777One-Handed Axe^000000",
			"Attack : ^777777250^000000",
			"Weight : ^77777720^000000",
			"Property : ^777777Earth^000000",
			"Weapon Level : ^7777775^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777Novice, Swordman, Thief, and Merchant Classes^000000"
		},
		slotCount = 3,
		ClassNum = 6,
		costume = false
	},
	[600055] = {
		unidentifiedDisplayName = "Two-handed Sword",
		unidentifiedResourceName = "¹Ù½ºÅ¸µå¼Òµå",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Chaos Sword",
		identifiedResourceName = "Å©·Ò¸ÞÅ»ÅõÇÚµå¼Òµå",
		identifiedDescriptionName = {
			"Forged in chaos, this blade pulses with wild, untamed power.",
			"_______________________",
			"^FF0000Indestructible in battle.^000000",
			"_______________________",
			"ASPD + 10.",
			"_______________________",
			"Reduce After Cast Delay by 10%.",
			"_______________________",
			"Reduce damage taken from Normal and Boss class enemies by 20%.",
			"_______________________",
			"Increase physical damage against all size enemies by 30%.",
			"_______________________",
			"For every refine level,",
			"increase physical damage against all size enemies by additional 12%.",
			"_______________________",
			"For every 2 refine level,",
			"POW + 3, MHP + 3%, increase Dragon's Breath, Dragon's Water Breath, and Wind Cutter damage by 20%.",
			"_______________________",
			"When refined to +11 or higher,",
			"reduce After Cast Delay by 20%, POW + 10.",
			"_______________________",
			"When refined to +12 or higher,",
			"All Basic Status + 20, ATK + 200, increase long-range physical damage by 20%.",
			"_______________________",
			"When refined to +13 or higher,",
			"MHP + 20%, reduce damage taken form Normal and Boss class enemies by 40%.",
			"_______________________",
			"When refined to +14 or higher,",
			"reduce damage taken from long-range physical and all property magic damage by 30%.",
			"",
			"When Weapon Grade is A,",
			"increase long-range physical damage by 30%.",
			"_______________________",
			"^FF0000Set Bonus:^000000",
			"^4D4DFFChaos Sword [2]^000000",
			"^4D4DFFRune Knight Seyren Card^000000",
			"",
			"POW + 30, CON + 30.",
			"Increase physical damage against all race enemies by 30%.",
			"",
			"When Weapon Grade is A,",
			"gain Endure status.",
			"_______________________",
			"^FF0000[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000 P.ATK + 15.",
			"^4D4DFF[Grade C]^000000 Reduce Fixed Casting Time by 0.5 seconds.",
			"^4D4DFF[Grade B]^000000 Increase Madness Crusher and Hack and Slash damage by 25%.",
			"^4D4DFF[Grade A]^000000 When dealing physical damage, there's a 5% chance to gain STR + 150, POW + 15 for 15 seconds.",
			"_______________________",
			"Type : ^777777Two-handed Sword^000000",
			"Atk : ^777777400^000000",
			"Weight : ^777777200^000000",
			"Weapon Level : ^7777775^000000",
			"Required Level : ^777777100^000000",
			"Class : ^777777Swordman^000000"
		},
		slotCount = 2,
		ClassNum = 3,
		costume = false
	},
	[1270142] = {
		unidentifiedDisplayName = "Unidentified Shadow Weapon",
		unidentifiedResourceName = "¿þÆù½¦µµ¿ì2",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Nebula Melee Shadow Weapon",
		identifiedResourceName = "¿þÆù½¦µµ¿ì2",
		identifiedDescriptionName = {
			"ATK +15 for every 2 refine levels.",
			"_______________________",
			"Increases melee physical damage by 2% for every 3 refine levels.",
			"_______________________",
			"If refined to +7 or higher,",
			"increases physical damage against targets of all races by 10%.",
			"_______________________",
			"If refined to +9 or higher,",
			"increases physical damage against Boss monster by 10%.",
			"_______________________",
			"If refined to +10 or higher,",
			"ignores 100% of physical defense of all races except Players.",
			"_______________________",
			"Class : ^777777Shadow Equipment^000000",
			"Location : ^777777Weapon^000000",
			"Weight : ^7777770^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1270143] = {
		unidentifiedDisplayName = "Unidentified Shadow Shield",
		unidentifiedResourceName = "½¯µå½¦µµ¿ì2",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Nebula Melee Shadow Shield",
		identifiedResourceName = "½¯µå½¦µµ¿ì2",
		identifiedDescriptionName = {
			"Reduces after cast delay by 1% for every 2 refine levels.",
			"_______________________",
			"Reduces fixed casting time by 0.2 seconds for every 3 refine levels.",
			"_______________________",
			"If refined to +7 or higher,",
			"All Stats +4, All Traits +4.",
			"_______________________",
			"If refined to +9 or higher,",
			"increases melee physical damage by 10%.",
			"_______________________",
			"If refined to +10 or higher,",
			"MaxHP +10%, MaxSP +10%.",
			"_______________________",
			"When equipped with Nebula Melee Shadow Weapon:",
			"P.ATK +10.",
			"Ignores 30% of RES of targets of all races.",
			"_______________________",
			"Class : ^777777Shadow Equipment^000000",
			"Location : ^777777Shield^000000",
			"Weight : ^7777770^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1270144] = {
		unidentifiedDisplayName = "Unidentified Shadow Weapon",
		unidentifiedResourceName = "³°Àº¿þÆù½¦µµ¿ì",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Nebula Range Shadow Weapon",
		identifiedResourceName = "³°Àº¿þÆù½¦µµ¿ì",
		identifiedDescriptionName = {
			"ATK +15 for every 2 refine levels.",
			"_______________________",
			"Increases ranged physical damage by 2% for every 3 refine levels.",
			"_______________________",
			"If refined to +7 or higher,",
			"increases physical damage against targets of all races by 10%.",
			"_______________________",
			"If refined to +9 or higher,",
			"increases physical damage against Boss monsters by 10%.",
			"_______________________",
			"If refined to +10 or higher,",
			"ignores 100% of physical defense of all races except Players.",
			"_______________________",
			"Class : ^777777Shadow Equipment^000000",
			"Location : ^777777Weapon^000000",
			"Weight : ^7777770^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1270145] = {
		unidentifiedDisplayName = "Unidentified Shadow Shield",
		unidentifiedResourceName = "³°Àº½¯µå½¦µµ¿ì",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Nebula Range Shadow Shield",
		identifiedResourceName = "³°Àº½¯µå½¦µµ¿ì",
		identifiedDescriptionName = {
			"Reduces after cast delay by 1% for every 2 refine levels.",
			"_______________________",
			"Reduces fixed casting time by 0.2 seconds for every 3 refine levels.",
			"_______________________",
			"If refined to +7 or higher,",
			"All Stats +4, All Traits +4.",
			"_______________________",
			"If refined to +9 or higher,",
			"increases ranged physical damage by 10%.",
			"_______________________",
			"If refined to +10 or higher,",
			"MaxHP +10%, MaxSP +10%.",
			"_______________________",
			"When equipped with Nebula Range Shadow Weapon:",
			"P.ATK +10.",
			"Ignores 30% of RES of targets of all races.",
			"_______________________",
			"Class : ^777777Shadow Equipment^000000",
			"Location : ^777777Shield^000000",
			"Weight : ^7777770^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1270146] = {
		unidentifiedDisplayName = "Unidentified Shadow Weapon",
		unidentifiedResourceName = "¿þÆù½¦µµ¿ì3",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Nebula Magic Shadow Weapon",
		identifiedResourceName = "¿þÆù½¦µµ¿ì3",
		identifiedDescriptionName = {
			"For every 2 upgrade levels:",
			"MATK +15.",
			"_______________________",
			"For every 3 upgrade levels:",
			"Increases magic damage of all property by 2%.",
			"_______________________",
			"If upgrade level is +7 or higher:",
			"Increases magic damage against enemies of all races by 10%.",
			"_______________________",
			"If upgrade level is +9 or higher:",
			"Increases magic damage against Boss monsters by 10%.",
			"_______________________",
			"If upgrade level is +10 or higher:",
			"Ignores 100% Magic Defense (MDEF) of all race monsters (Except Players).",
			"_______________________",
			"Class : ^777777Shadow Equipment^000000",
			"Location : ^777777Weapon^000000",
			"Weight : ^7777770^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1270147] = {
		unidentifiedDisplayName = "Unidentified Shadow Shield",
		unidentifiedResourceName = "½¯µå½¦µµ¿ì3",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Nebula Magic Shadow Shield",
		identifiedResourceName = "½¯µå½¦µµ¿ì3",
		identifiedDescriptionName = {
			"For every 2 upgrade levels:",
			"Reduces after-cast delay by 1%.",
			"_______________________",
			"For every 3 upgrade levels:",
			"Reduces fixed casting time by 0.2 seconds.",
			"_______________________",
			"If upgrade level is +7 or higher:",
			"All Stats +4, All Traits +4.",
			"_______________________",
			"If upgrade level is +9 or higher:",
			"Increases magic damage of all property by 10%.",
			"_______________________",
			"If upgrade level is +10 or higher:",
			"MaxHP +10%, MaxSP +10%.",
			"_______________________",
			"When equipped with Nebula Magic Shadow Weapon:",
			"S.MATK +10.",
			"Ignores 30% MRES of enemies of all races.",
			"_______________________",
			"Class : ^777777Shadow Equipment^000000",
			"Location : ^777777Shield^000000",
			"Weight : ^7777770^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1270192] = {
		unidentifiedDisplayName = "Unidentified Shadow Armor",
		unidentifiedResourceName = "¾Æ¸Ó½¦µµ¿ì3",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Snow Flower Magic Shadow Armor",
		identifiedResourceName = "¾Æ¸Ó½¦µµ¿ì3",
		identifiedDescriptionName = {
			"For every 2 upgrade levels:",
			"S.MATK +1.",
			"_______________________",
			"For every 3 upgrade levels:",
			"Increases magic damage of all property by 2%.",
			"_______________________",
			"If upgrade level is +7 or higher:",
			"MaxHP +10%, RES +30.",
			"_______________________",
			"If upgrade level is +9 or higher:",
			"Reduces after-cast delay by 10%.",
			"_______________________",
			"If upgrade level is +10 or higher:",
			"Increases magic damage against enemies of all properties by 10%.",
			"_______________________",
			"Class : ^777777Shadow Equipment^000000",
			"Location : ^777777Armor^000000",
			"Weight : ^7777770^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1270193] = {
		unidentifiedDisplayName = "Unidentified Shadow Shoes",
		unidentifiedResourceName = "½´Áî½¦µµ¿ì3",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Snow Flower Magic Shadow Shoes",
		identifiedResourceName = "½´Áî½¦µµ¿ì3",
		identifiedDescriptionName = {
			"For every 2 upgrade levels:",
			"S.MATK +1.",
			"_______________________",
			"For every 3 upgrade levels:",
			"ASPD +5%.",
			"_______________________",
			"If upgrade level is +7 or higher:",
			"MaxSP +10%, MRES +30.",
			"_______________________",
			"If upgrade level is +9 or higher:",
			"Reduces fixed casting time by 0.3 seconds.",
			"_______________________",
			"If upgrade level is +10 or higher:",
			"Increases magic damage against enemies of all sizes by 10%.",
			"_______________________",
			"When equipped with Snow Flower Magic Shadow Armor:",
			"Increases magic damage of all property by 4%.",
			"If the combined upgrade level is 21 or higher:",
			"Grants [Endure] effect at all times.",
			"_______________________",
			"Class : ^777777Shadow Equipment^000000",
			"Location : ^777777Shoes^000000",
			"Weight : ^7777770^000000",
			"Required Level : ^777777100^000000",
			"Jobs : ^777777All Jobs^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
