	[470456] = {
		unidentifiedDisplayName = "Shoes",
		unidentifiedResourceName = "부츠",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "Ayothaya Adventurer's Boots-LT",
		identifiedResourceName = "Gluttony_Variant_Shoes",
		identifiedDescriptionName = {
			"Shoes for brave adventurers, worn to overcome all obstacles and confidently set forth on a new journey.",
			"_______________________",
			"Increases melee and ranged physical damage by 12% and MATK +12%.",
			"ASPD +15%.",
			"MaxHP +15%.",
			"MaxSP +10%.",
			"_______________________",
			"ATK +15 and MATK +15 for every 2 refine levels.",
			"_______________________",
			"If refined to +7 or higher,",
			"P.ATK +10, S.MATK +10.",
			"_______________________",
			"If refined to +9 or higher,",
			"reduces variable casting time by 20%, reduces fixed casting time by 0.5 seconds.",
			"_______________________",
			"If refined to +12 or higher,",
			"increases physical and magical damage against targets of all properties by 15%.",
			"_______________________",
			"When equipped with 6th Anniversary Ayothaya Ring:",
			"Has a 6% chance to restore 1% of physical damage dealt as HP and SP when dealing physical attacks.",
			"Has a 6% chance to restore 1,000 HP and 100 SP 8 times over 10 seconds when dealing magical attacks.",
			"Increases physical and magical damage against targets of all sizes by 15%.",
			"",
			"If Ayothaya Adventurer's Boots is Grade A or higher and equipped with 6th Anniversary Ayothaya Ring:",
			"Increases experience gained from defeating monsters by 10%.",
			"Increases item drop rate by 10%.",
			"Increases physical and magical damage against targets of all races except Players by 15%.",
			"",
			"When equipped with 6th Anniversary Ayothaya Ring and Upgrade Memory of Thanatos Card:",
			"Ignores 40% of physical defense of targets of all races.",
			"_______________________",
			"^CC3D3D[Grade Bonus]^000000",
			"^4D4DFF[Grade D]^000000: Reduces fixed casting time by 0.5 seconds.",
			"^4D4DFF[Grade C]^000000: Increases physical damage by 20%, Critical damage +20%, increases magical damage against targets of all properties by 25%.",
			"^4D4DFF[Grade B]^000000: P.ATK +10, S.MATK +10.",
			"^4D4DFF[Grade A]^000000: All Stats +2 and All Traits +2 for every 1 refine level.",
			"_______________________",
			"^0000CCType:^000000 Shoes",
			"^0000CCDefense:^000000 20",
			"^0000CCWeight:^000000 20",
			"^0000CCArmor Level:^000000 2",
			"_______________________",
			"^0000CCRequirement:^000000",
			"Base Level 100"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[491070] = {
		unidentifiedDisplayName = "Accessory (Left)",
		unidentifiedResourceName = "링",
		unidentifiedDescriptionName = { "Unidentified. Can be identified with Magnifier." },
		identifiedDisplayName = "6th Anniversary Ayothaya Ring-LT",
		identifiedResourceName = "Gluttony_Expert_Ring",
		identifiedDescriptionName = {
			"A ring created to celebrate the 6th anniversary. It overflows with the power of blessings and memories of past adventures.",
			"_______________________",
			"[Refinable]",
			"_______________________",
			"All Stats +10, All Traits +10.",
			"Increases melee and ranged physical damage by 2% and MATK +2% for every 1 refine level.",
			"_______________________",
			"If refined to +7 or higher,",
			"P.ATK +6, S.MATK +6.",
			"_______________________",
			"If refined to +9 or higher,",
			"reduces after cast delay by 15%.",
			"_______________________",
			"If refined to +12 or higher,",
			"increases physical and magical damage against targets of all races except Players by 15%,",
			"Ignores 40% of physical and magical defense of targets of all races except Players.",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"[Grade D]: Reduces fixed casting time by 0.5 seconds.",
			"[Grade C]: Reduces damage taken from Boss monsters by 15%.",
			"[Grade B]: RES +120, MRES +120, Perfect Dodge +30.",
			"[Grade A]: Increases item drop rate by 10%, Increases experience gained from defeating monsters by 10%.",
			"_______________________",
			"Class : ^777777Accessory (Left)^000000",
			"Defense : ^7777770^000000",
			"Weight : ^77777720^000000",
			"Required Level : ^777777200^000000",
			"Equipped : ^777777All Jobs^000000"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
